# Generated by Django 6.1 on 2026-09-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="заголовок статьи",
                        max_length=255,
                        verbose_name="заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="текст статьи",
                        null=True,
                        verbose_name="текст",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="изображение статьи",
                        null=True,
                        upload_to="previews/",
                        verbose_name="изображение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_published",
                    models.BooleanField(default=False, help_text="Признак публикации"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Количество просмотров"
                    ),
                ),
            ],
        ),
    ]
