# Generated by Django 6.1 on 2026-09-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ("title",),
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="текст"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=True, help_text="Признак публикации"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="previews/", verbose_name="изображение"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=255, verbose_name="заголовок"),
        ),
    ]
